base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Sanzo00"
repo_name: "daily-paper"
show_authors: True
show_links: True
max_results: 100

publish_readme: False
publish_gitpage: True

# file paths
json_readme_path: './docs/arxiv-daily.json'
json_gitpage_path: './docs/arxiv-daily-web.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'

# keywords to search
keywords:

    "RAG":
        logic: AND
        filters:
        - ["LLM", "RAG", "KV"]
        - ["LLM", "RAG", "KG"]
        - ["LLM", "RAG", "Graph"]


    "LLM":
        logic: AND
        filters:
        ## - ["LLM", "KV", "Inference"]
        - ["LLM", "KV", "Serving"]
        - ["LLM", "KV", "Retrieve"]
        - ["LLM", "KV", "Scheduling"]
        - ["LLM", "KV", "Agent"]
        - ["LLM", "KV", "Reasoning"]
        - ["LLM", "KV", "Thinking"]
        - ["LLM", "KV", "Prefix"]
        - ["LLM", "Agent", "Scheduling"]
        - ["Agent", "Scheduling", "KV"]


    "GNN":
        logic: AND
        filters:
        - ["GNN", "Training", "System", "GPU"]
        - ["GNN", "Training", "System", "Disk"]
        - ["GNN", "Training", "System", "Partition"]
        - ["GNN", "Training", "System", "Communication"]
        - ["GNN", "Inference", "System", "Partition"]
        - ["GNN", "Inference", "System", "Communication"]
        - ["GNN", "System", "Asynchronous"]


        # filters: [
        #     "GNN Training", "Distributed GNN", "Sample-based GNN Training", "Full-Graph GNN Training",
        #     "Large-scale Graph Neural Network", "GNN System Optimization", "GNN Partitioning",
        #     "Graph Training Pipeline", "Graph Training Parallelism", "GNN Scheduling", "GNN Training Evaluation",
        #     "Hybrid CPU-GPU GNN Training", "GNN Communication Optimization", "Graph Neural Network Serving"
        # ]
